### ISSUE TITLE
.mkv file support

### ISSUE THREAD

**Issue by andrius-k** [freshplanet/ANE-Video#2]
When I try to play .mov file it works just fine, but .mkv does not. Is it just not compatable witj iOS video player or is it some kind of a bug?

**Comment by dornad** [comment]
ANE-Video relies on Apple's MPMoviePlayerController.

MKV are just container files, you might want to check the codec you are using against Apple's specs.

As a rule of thumb, I use MP4 or MOV files.

Edit:  In order to play a non supported format, you need to write your own decoder which may be very difficult. You have to study each format, the relative documentation etc. Otherwise, you can look for open source codecs in obj-c, or port them from another language.

**Comment by andrius-k** [comment]
Thanks allot for info :)
